### PR TITLE
Pb add google auth

### PR DESCRIPTION
**Pull request by opsline-paul**
For google auth

### CODE REVIEW

**Comment by opsline-radek** [comment]
looks good so far.

Do SSH logins to the VPN server also go through google auth?

**Comment by opsline-paul** [comment]
Nope,  but it's certainly possible. Want me to add that?

**Comment by opsline-radek** [comment]
No, please don't :) I think it should be then possible to have non-local users have access to VPN. We should try that later.

**Comment by opsline-joey** [comment]
@opsline-chetan we may need this in the future if they want MFA and don't want to do duo, might be worth following up to identify why we did not merge this into master yet.

**Review by opsline-radek — APPROVED** [review]
this is ready, reviewed and tested loooong time ago. Can be merged.

**Comment by opsline-joey** [comment]
@opsline-radek do you want to bump up our version right now master is at 0.1.6 , then we should probably merge with rebase ( I believe github ui streamlines this now)

Unfortunately I do not have permissions to merge and such just FYI so someone else will need to merge this in post the above.

**Pull request merged**
